#gt915 touchpanel driver


obj-$(CONFIG_TY_GT9XX_TOUCHPANEL_DRIVER)	+= ty_gt9xx.o
#gt915 update file
obj-$(CONFIG_TY_GT9XX_TOUCHPANEL_UPDATE)	+= ty_gt9xx_update.o
#debug tool
obj-$(CONFIG_TY_GT9XX_TOUCHPANEL_DEBUG)		+= ty_goodix_tool.o
